@3
Feature: Spotify feature set
  As a <role>
  I can <do something>
  So that <I can get some value>

Scenario: Spotify get all tracks
  Given the starter-service
  When I GET the endpoint "/api/v1/tracks?providers=spotify&q=how+can+I+compete"
  Then I should get a 200 with a body of
  """
  [{"tracks":{"href":"https://api.spotify.com/v1/search?query=how+can+I+compete&type=track&offset=0&limit=1","items":[{"album":{"album_type":"album","artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/52pNByiBWx6SVMMqqcCA74"},"href":"https://api.spotify.com/v1/artists/52pNByiBWx6SVMMqqcCA74","id":"52pNByiBWx6SVMMqqcCA74","name":"The Magic Gang","type":"artist","uri":"spotify:artist:52pNByiBWx6SVMMqqcCA74"}],"available_markets":["AD","AE","AR","AT","AU","BE","BG","BH","BO","BR","CA","CH","CL","CO","CR","CY","CZ","DE","DK","DO","DZ","EC","EE","EG","ES","FI","FR","GB","GR","GT","HK","HN","HU","ID","IE","IL","IS","IT","JO","JP","KW","LB","LI","LT","LU","LV","MA","MC","MT","MX","MY","NI","NL","NO","NZ","OM","PA","PE","PH","PL","PS","PT","PY","QA","RO","SA","SE","SG","SK","SV","TH","TN","TR","TW","US","UY","VN","ZA"],"external_urls":{"spotify":"https://open.spotify.com/album/468IjYKaexANvGfdtxMdwd"},"href":"https://api.spotify.com/v1/albums/468IjYKaexANvGfdtxMdwd","id":"468IjYKaexANvGfdtxMdwd","images":[{"height":640,"url":"https://i.scdn.co/image/fab5a7c4204c246577ff56783c0237be67fe0305","width":640},{"height":300,"url":"https://i.scdn.co/image/ecbad8b44fd6ae693bdf3b50680929bad903e99d","width":300},{"height":64,"url":"https://i.scdn.co/image/573623ede1cc9aaf18728a3d734c176e0fec6ac0","width":64}],"name":"The Magic Gang (Deluxe)","release_date":"2018-03-16","release_date_precision":"day","total_tracks":16,"type":"album","uri":"spotify:album:468IjYKaexANvGfdtxMdwd"},"artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/52pNByiBWx6SVMMqqcCA74"},"href":"https://api.spotify.com/v1/artists/52pNByiBWx6SVMMqqcCA74","id":"52pNByiBWx6SVMMqqcCA74","name":"The Magic Gang","type":"artist","uri":"spotify:artist:52pNByiBWx6SVMMqqcCA74"}],"available_markets":["AD","AE","AR","AT","AU","BE","BG","BH","BO","BR","CA","CH","CL","CO","CR","CY","CZ","DE","DK","DO","DZ","EC","EE","EG","ES","FI","FR","GB","GR","GT","HK","HN","HU","ID","IE","IL","IS","IT","JO","JP","KW","LB","LI","LT","LU","LV","MA","MC","MT","MX","MY","NI","NL","NO","NZ","OM","PA","PE","PH","PL","PS","PT","PY","QA","RO","SA","SE","SG","SK","SV","TH","TN","TR","TW","US","UY","VN","ZA"],"disc_number":1,"duration_ms":174200,"explicit":false,"external_ids":{"isrc":"GBAHT1700028"},"external_urls":{"spotify":"https://open.spotify.com/track/4UdONZMZRNR3qhLTEbPYLI"},"href":"https://api.spotify.com/v1/tracks/4UdONZMZRNR3qhLTEbPYLI","id":"4UdONZMZRNR3qhLTEbPYLI","is_local":false,"name":"How Can I Compete","popularity":54,"preview_url":"https://p.scdn.co/mp3-preview/d64ceea133091f3db054b23d29a58c3f6fbd96c1?cid=14743e62b4e24bd4b94763e14dba654d","track_number":10,"type":"track","uri":"spotify:track:4UdONZMZRNR3qhLTEbPYLI"}],"limit":1,"next":"https://api.spotify.com/v1/search?query=how+can+I+compete&type=track&offset=1&limit=1","offset":0,"previous":null,"total":23}}]
  """